finalprojectSinchon/backend

src/main/java/com/finalproject/airport/airplane/Airplane.java
src/main/java/com/finalproject/airport/airplane/AirplaneDTO.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/controller/baggageClaimController.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/dto/BaggageClaimDTO.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaim.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaimType.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/repository/BaggageClaimRepository.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java
src/main/java/com/finalproject/airport/airplane/checkincounter/controller/CheckinCounterController.java
src/main/java/com/finalproject/airport/airplane/checkincounter/dto/CheckinCounterDTO.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounter.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounterType.java
src/main/java/com/finalproject/airport/airplane/checkincounter/repository/CheckinCounterRepository.java
src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java
src/main/java/com/finalproject/airport/airplane/gate/controller/GateController.java
src/main/java/com/finalproject/airport/airplane/gate/dto/GateDTO.java
src/main/java/com/finalproject/airport/airplane/gate/entity/Gate.java
src/main/java/com/finalproject/airport/airplane/gate/entity/GateType.java
src/main/java/com/finalproject/airport/airplane/gate/repository/GateRepository.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java

- 제목 : feat(13): 패키지
<br/>
- 비행기(수화물 수취대, 탑승구, 체크인카운터) 패키지 구조 
- controller 
- entity
- dto
- repository
- service
<br/>
<br/>
- [backend #13 ]
<br/>

[2024-07-15] 비행기(체크인카운터,탑승구,수화물 수취대) 패키지

---

src/main/java/com/finalproject/airport/auth/config/SecurityConfig.java
src/main/java/com/finalproject/airport/auth/filter/JWTFilter.java
src/main/java/com/finalproject/airport/auth/filter/LoginFilter.java
src/main/java/com/finalproject/airport/storage/entity/StorageEntity.java
src/main/java/com/finalproject/airport/storage/entity/StorageType.java
src/main/java/com/finalproject/airport/store/controller/StoreController.java
src/main/java/com/finalproject/airport/store/dto/StoreDTO.java
src/main/java/com/finalproject/airport/store/dto/StoreRegistDTO.java
src/main/java/com/finalproject/airport/store/entity/StoreEntity.java
src/main/java/com/finalproject/airport/store/entity/StoreType.java
src/main/java/com/finalproject/airport/store/entity/StoreWork.java
src/main/java/com/finalproject/airport/store/repository/StoreRepository.java
src/main/java/com/finalproject/airport/store/service/StoreService.java

- 제목 : #15 
<br/>
- Store 등록 전체조회 상세조회 삭제 구현
<br/>
<br/>
- Entity 만들기
<br/>
<br/>

[2024-07-15] Store API

---

src/main/java/com/finalproject/airport/facilities/controller/FacilitiesController.java
src/main/java/com/finalproject/airport/facilities/controller/merong.java
src/main/java/com/finalproject/airport/facilities/dto/FacilitiesDTO.java
src/main/java/com/finalproject/airport/facilities/dto/FacilitiesStatus.java
src/main/java/com/finalproject/airport/facilities/dto/facilitesType.java
src/main/java/com/finalproject/airport/facilities/dto/facilitiesClass.java
src/main/java/com/finalproject/airport/facilities/entity/Facilities.java
src/main/java/com/finalproject/airport/facilities/repository/FacilitiesRepository.java
src/main/java/com/finalproject/airport/facilities/service/FacilitiesService.java

- 제목 : 편의시설 API
<br/>
편의시설 Entity 전체조회  구
<br/>
Entity 만들기
<br/>
<br/>

[2024-07-15]편의시설 API

---

src/main/java/com/finalproject/airport/store/controller/StoreController.java
src/main/java/com/finalproject/airport/store/dto/StoreDTO.java
src/main/java/com/finalproject/airport/store/service/StoreService.java

<br/>
- Store Entity CRUD 완성
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-15] Store API 완성

---

src/main/java/com/finalproject/airport/inspection/controller/InspectionController.java
src/main/java/com/finalproject/airport/inspection/dto/InspectionDTO.java
src/main/java/com/finalproject/airport/inspection/dto/InspectionRegistDTO.java
src/main/java/com/finalproject/airport/inspection/entity/InspectionEntity.java
src/main/java/com/finalproject/airport/inspection/entity/InspectionRegistEntity.java
src/main/java/com/finalproject/airport/inspection/respository/InspectionRepository.java
src/main/java/com/finalproject/airport/inspection/service/InspectionService.java

(확인 후 지워주세요)
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

inspection

---

src/main/java/com/finalproject/airport/facilities/controller/FacilitiesController.java
src/main/java/com/finalproject/airport/facilities/dto/FacilitiesDTO.java
src/main/java/com/finalproject/airport/facilities/entity/FacilitiesEntity.java
src/main/java/com/finalproject/airport/facilities/entity/FacilitiesStatus.java
src/main/java/com/finalproject/airport/facilities/entity/facilitesType.java
src/main/java/com/finalproject/airport/facilities/entity/facilitiesClass.java
src/main/java/com/finalproject/airport/facilities/repository/FacilitiesRepository.java
src/main/java/com/finalproject/airport/facilities/service/FacilitiesService.java

- 제목 : 편의시설 API 패키지 구조수정, 상세조회 기능추가
<br/>
편의시설 API 패키지 구조수정, 상세조회 기능추가
<br/>
<br/>
<br/>

[2024-07-15]편의시설 API 패키지 구조수정, 상세조회 기능추가

---

src/main/java/com/finalproject/airport/airplane/Airplane.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/controller/baggageClaimController.java
src/main/java/com/finalproject/airport/airplane/gate/controller/GateController.java
src/main/java/com/finalproject/airport/airplane/gate/dto/GateDTO.java
src/main/java/com/finalproject/airport/airplane/gate/entity/Gate.java
src/main/java/com/finalproject/airport/airplane/gate/repository/GateRepository.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java

- 제목 : feat(27): 기능명
<br/>
탑승구
- 전체 조회
- 상세 조회
- 수정
- soft delete
- 등록
<br/>
- [backend #27 ]
<br/>

[2024-07-15] 탑승구 CRUD

---

src/main/java/com/finalproject/airport/airplane/baggageclaim/controller/BaggageClaimController.java
src/main/java/com/finalproject/airport/facilities/dto/FacilitiesDTO.java
src/main/java/com/finalproject/airport/facilities/entity/FacilitesType.java
src/main/java/com/finalproject/airport/facilities/entity/FacilitiesClass.java
src/main/java/com/finalproject/airport/facilities/entity/FacilitiesEntity.java

- 제목 : feat(30): 클래스명 수정
<br/>
소문자로 되어 있던 클래스명 수정
<br/>
- [backend #30 ]
<br/>

[2024-07-17] 클래스명 수정

---

src/main/java/com/finalproject/airport/auth/config/CorsMvcConfig.java
src/main/java/com/finalproject/airport/auth/config/SecurityConfig.java

- 제목 : feat( #54 ): CORS
<br/>
-  헤더필터 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-17] CORS

---

src/main/java/com/finalproject/airport/auth/controller/AuthController.java
src/main/java/com/finalproject/airport/member/dto/JoinDTO.java
src/main/java/com/finalproject/airport/member/dto/UserDTO.java
src/main/java/com/finalproject/airport/member/entity/UserEntity.java
src/main/java/com/finalproject/airport/member/service/CustomUserDetails.java
src/main/java/com/finalproject/airport/member/service/JoinService.java

- 제목 :  회원가입 중복검증 로직 추가
<br/>
-회원가입시 중복확인하고 있을 시 ResponseEntity 로 Bad_Request 보냄.
axios .catch 로 잡게 수정
<br/>
- 적어주세요
<br/>
<br/>

회원가입 중복검증 로직 추가

---

src/main/java/com/finalproject/airport/auth/controller/AuthController.java
src/main/java/com/finalproject/airport/member/dto/UserModifyDTO.java
src/main/java/com/finalproject/airport/member/entity/UserEntity.java
src/main/java/com/finalproject/airport/member/service/JoinService.java

- 제목 : feat(#62 ): 수정 APi 작성
<br/>
- 유저 이름, 전화번호, 주소, 이메일, 내정보 수정할 수 있게 변경
- builder 변경
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-17] 내정보 수정 api 추가

---

src/main/java/com/finalproject/airport/auth/controller/AuthController.java
src/main/java/com/finalproject/airport/member/dto/UserPasswordCheckDTO.java
src/main/java/com/finalproject/airport/member/service/JoinService.java

- 제목 : feat(#64 ): 비밀번호 일치 확인 api 추가
<br/>
- bCryptPasswordEncoder 로 일치여부 확인
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-17] 비밀번호 일치 확인 api 추가

---

src/main/java/com/finalproject/airport/auth/controller/AuthController.java

- 제목 : feat(#12): 비밀번호 변경 api 추가
<br/>
- 비밀번호 변경 로직 추가
- service 계층에서 새비밀번호 비밀번호 확인 일치 확인
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-17] 비밀번호 변경 api 추가

---

src/main/java/com/finalproject/airport/maintenance/controller/MaintenanceController.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java

- 제목 : feat(58): 정비 CRUD
<br/>
- 정비 등록
<br/>
- 정비 수정,삭제 해야 함.
<br/>
- [backend #58 ](이슈 주소)
<br/>

[2024-07-17] 정비 등록

---

src/main/java/com/finalproject/airport/airplane/baggageclaim/dto/BaggageClaimDTO.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaim.java
src/main/java/com/finalproject/airport/airplane/checkincounter/controller/CheckinCounterController.java
src/main/java/com/finalproject/airport/airplane/checkincounter/dto/CheckinCounterDTO.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounter.java
src/main/java/com/finalproject/airport/airplane/checkincounter/repository/CheckinCounterRepository.java
src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java
src/main/java/com/finalproject/airport/airplane/gate/controller/GateController.java
src/main/java/com/finalproject/airport/airplane/gate/dto/GateDTO.java

- 제목 : feat(50,51): 체크인 카운터
<br/>
- 체크인카운터 등록
- 체크인카운터 전체조회
- 체크인카운터  상세조회
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #50 ]
- [backend #51  ]
<br/>

체크인카운터 등록/조회

---

src/main/java/com/finalproject/airport/maintenance/controller/MaintenanceController.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java
src/main/resources/application.yml

- 제목 : feat(issue 번호): maintenance 조회
<br/>
- 조회에서 service 부분 수정
<br/>
- 리엑트와의 연결
- 제대로 작동하는지 확인하고 오류 발생시, 수정하기
<br/>
- [backend #56 ](이슈 주소)
<br/>

[2024-07-18] 정비 service 수정

---

src/main/java/com/finalproject/airport/inspection/controller/InspectionController.java
src/main/java/com/finalproject/airport/inspection/dto/InspectionDTO.java
src/main/java/com/finalproject/airport/inspection/service/InspectionService.java

- 제목 : feat(issue 번호):   점검 crud 등록 최종본
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024.07-18] inspection api 등록 확인 crud

---

src/main/java/com/finalproject/airport/maintenance/controller/MaintenanceController.java
src/main/java/com/finalproject/airport/maintenance/repository/MaintenanceRepository.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java

- 제목 : feat(issue 번호): 정비 상세 조회
<br/>
- 정비 상세 조회 성공
<br/>
<br/>
- 정비 등록
- 정비 수정
- 정비 삭제
<br/>
- [backend #56 ](이슈 주소)
<br/>

[2024-07-18] 정비 상세 조회

---

src/main/java/com/finalproject/airport/auth/filter/LoginFilter.java

[2024-07-17] 토큰 만료시간 24시간으로 증가

---

src/main/java/com/finalproject/airport/auth/controller/AuthController.java
src/main/java/com/finalproject/airport/member/dto/UserDTO.java
src/main/java/com/finalproject/airport/member/entity/UserEntity.java
src/main/java/com/finalproject/airport/member/service/CustomUserDetails.java
src/main/java/com/finalproject/airport/member/service/JoinService.java
src/main/java/com/finalproject/airport/store/controller/StoreController.java

- 제목  프로필 이미지 api 추가
<br/>
- 이미지 저장 api 추가
<br/>
<br/>
<br/>

[2024-07-19] 프로필 이미지 추가

---

src/main/java/com/finalproject/airport/store/controller/StoreController.java
src/main/java/com/finalproject/airport/store/dto/StoreAPIDTO.java
src/main/java/com/finalproject/airport/store/dto/StoreDTO.java
src/main/java/com/finalproject/airport/store/entity/StoreEntity.java
src/main/java/com/finalproject/airport/store/service/StoreService.java

- 제목 : openAPI DB 등록 api 추가
<br/>
- 공공데이터포털 컬럼값과 내 DB 컬럼값 일치 시킴.
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-19] openAPI DB 등록 api 추가

---

src/main/java/com/finalproject/airport/airplane/gate/controller/GateController.java
src/main/java/com/finalproject/airport/airplane/gate/dto/GateDTO.java
src/main/java/com/finalproject/airport/airplane/gate/entity/Gate.java

- 제목 : feat(78): 탑승구 수정
<br/>
- 탑승구 수정 기능
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #78 ]
<br/>

[2024-07-19] 탑승구 수정 기능

---

src/main/java/com/finalproject/airport/airplane/gate/entity/Gate.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java
src/main/java/com/finalproject/airport/common/IsActiveEmbeddable.java
src/main/java/com/finalproject/airport/store/service/StoreService.java

Embeddable 추가
사용법
1. 엔티티에 컬럼 추가한다.
2. 서비스에서 컬럼값 바꾸는 방법

[2024-07-19] Embeddable 추가

---

src/main/java/com/finalproject/airport/inspection/controller/InspectionController.java
src/main/java/com/finalproject/airport/inspection/dto/InspectionDTO.java
src/main/java/com/finalproject/airport/inspection/entity/InspectionEntity.java
src/main/java/com/finalproject/airport/inspection/respository/InspectionRepository.java
src/main/java/com/finalproject/airport/inspection/service/InspectionService.java

- 제목 : feat(issue 번호): inspection 안전 점검 전체 조회 연결
<br/>
-  inspection 안전 점검 전체 조회 연결
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024.07-18] inspection 안전 점검 전체 조회 연결

---

src/main/java/com/finalproject/airport/airplane/checkincounter/controller/CheckinCounterController.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounter.java
src/main/java/com/finalproject/airport/airplane/checkincounter/repository/CheckinCounterRepository.java
src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java
src/main/java/com/finalproject/airport/airplane/gate/controller/GateController.java

- 제목 : feat52,53): 체크인 카운터 수정/삭제
<br/>
- 체크인카운터 수정
- 체크인 카운터 soft delete
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #52 #53]
<br/>

[2024-07-19] 체크인 카운터 수정/삭제

---

src/main/java/com/finalproject/airport/storage/controller/StorageController.java
src/main/java/com/finalproject/airport/storage/dto/StorageDTO.java
src/main/java/com/finalproject/airport/storage/dto/StorageRegistDTO.java
src/main/java/com/finalproject/airport/storage/entity/Department.java
src/main/java/com/finalproject/airport/storage/entity/StorageEntity.java
src/main/java/com/finalproject/airport/storage/entity/StorageType.java
src/main/java/com/finalproject/airport/storage/repository/StorageRepository.java
src/main/java/com/finalproject/airport/storage/service/StorageService.java

(확인 후 지워주세요)
<br/>
- 창고 엔티티
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [레포 이름 #94 ](이슈 주소)
<br/>

[2024-07-19] storage 엔티티

---

src/main/java/com/finalproject/airport/airplane/baggageclaim/controller/BaggageClaimController.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaim.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/repository/BaggageClaimRepository.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java

- 제목 : feat(90): 수화물 수취대 조회
<br/>
- 수화물 수취대 전체 조회
- 수화물 수취대 상세 조회
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #90]
<br/>

[2024-07-19] 수화물 수취대 조회

---

src/main/java/com/finalproject/airport/airplane/baggageclaim/controller/BaggageClaimController.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java

- 제목 : feat(i89): 수화물 수취대 등록
<br/>
- 수화물 수취대 등록
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #89]
<br/>

[2024-07-19] 수화물 수취대 등록

---

src/main/java/com/finalproject/airport/airplane/Airplane.java
src/main/java/com/finalproject/airport/airplane/checkincounter/dto/CheckinCounterDTO.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounter.java
src/main/java/com/finalproject/airport/airplane/gate/dto/GateDTO.java
src/main/java/com/finalproject/airport/airplane/gate/entity/Gate.java

- 제목 : feat(issue 번호): 비행기  컬럼   수정
<br/>
- 비행기 엔티티 지연시간 컬럼 추가
- 비행기 DTO 지연시간 컬럼 추가
- 탑승구 엔티티 지연시간 컬럼 삭제
- 탑승구 DTO 지연시간 컬럼 삭제
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-21] 비행기 엔티티 컬럼 수정

---

src/main/java/com/finalproject/airport/airplane/airplane/DTO/AirplaneDTO.java
src/main/java/com/finalproject/airport/airplane/airplane/DTO/ArrivalAirplaneDTO.java
src/main/java/com/finalproject/airport/airplane/airplane/DTO/DepartureAirplaneDTO.java
src/main/java/com/finalproject/airport/airplane/airplane/Entity/Airplane.java
src/main/java/com/finalproject/airport/airplane/airplane/controller/AirplaneController.java
src/main/java/com/finalproject/airport/airplane/airplane/repository/AirplaneRepository.java
src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/controller/BaggageClaimController.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/dto/BaggageClaimDTO.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaim.java
src/main/java/com/finalproject/airport/airplane/checkincounter/dto/CheckinCounterDTO.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounter.java
src/main/java/com/finalproject/airport/airplane/gate/dto/GateDTO.java
src/main/java/com/finalproject/airport/airplane/gate/entity/Gate.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java
src/main/java/com/finalproject/airport/storage/controller/StorageController.java

- 제목 : feat(100): 비행기 조회
<br/>
- 비행기 전체 조회
- 비행기 상세  조회
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #100]
<br/>

[2024-07-21] 비행기 조회

---

build.gradle
src/main/java/com/finalproject/airport/airplane/airplane/DTO/AirplaneDTO.java
src/main/java/com/finalproject/airport/airplane/airplane/Entity/Airplane.java
src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java
src/main/java/com/finalproject/airport/config/BeanConfiguration.java

- 제목 : feat(105): 비행기 api 
<br/>
- 비행기 api 데이터 가져오기 설정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #105]
<br/>

[2024-07-21] 비행기 api

---

src/main/java/com/finalproject/airport/airplane/airplane/controller/AirplaneController.java
src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java
src/main/java/com/finalproject/airport/maintenance/controller/MaintenanceController.java
src/main/java/com/finalproject/airport/maintenance/dto/MaintenanceDTO.java
src/main/java/com/finalproject/airport/maintenance/entity/MaintenanceEntity.java
src/main/java/com/finalproject/airport/maintenance/repository/MaintenanceRepository.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java

- 제목 : feat(57): 정비 수정
<br/>
- 정비 수정 업데이트
<br/>
" width="50%" height="50%"/>
<br/>
- 정비 나머지 crud
- 리엑트 연결
<br/>
- [backend #57 ](이슈 주소)
<br/>

[2024-07-22] maintenance 수정

---

.gitignore
build.gradle
src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java
src/main/java/com/finalproject/airport/auth/filter/JWTFilter.java
src/main/java/com/finalproject/airport/config/SwaggerConfig.java
src/main/java/com/finalproject/airport/store/controller/StoreController.java

- 제목 : swagger 시큐리티 필터 설정
<br/>
-  swagger 시큐리티 필터 설정
<br/>
<br/>

[2024-07-22] swagger 시큐리티 필터 설정

---

src/main/java/com/finalproject/airport/maintenance/controller/MaintenanceController.java
src/main/java/com/finalproject/airport/maintenance/entity/MaintenanceEntity.java
src/main/java/com/finalproject/airport/maintenance/repository/MaintenanceRepository.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java

- 제목 : feat(i59): 정비 삭제
<br/>
- 정비 삭제 완료
<br/>
<br/>
- 전체 조회 find양식 바꾸기
- 리엑트 연결
<br/>
- [backend #59 ](이슈 주소)
<br/>

[2024-07-22] 정비 삭제

---

src/main/java/com/finalproject/airport/storage/controller/StorageController.java
src/main/java/com/finalproject/airport/storage/entity/StorageEntity.java
src/main/java/com/finalproject/airport/storage/service/StorageService.java
src/main/resources/application.yml

- 제목 : feat(108): storage 삭제
<br/>
- 창고 삭제
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #108 ](이슈 주소)
<br/>

storage 삭제

---

src/main/java/com/finalproject/airport/maintenance/controller/MaintenanceController.java
src/main/java/com/finalproject/airport/maintenance/repository/MaintenanceRepository.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java

- 제목 : feat(56): 정비 전체 조회
<br/>
- 정비 전체 조회의 isActive 활성화 시킴
<br/>
<br/>
- 정비 등록
- 정비 백엔드와 리엑트 연결
<br/>
- [backend #56 ](이슈 주소)
<br/>

[2024-07-22] 정비 전체 조회 isActive 활성화

---

src/main/java/com/finalproject/airport/maintenance/controller/MaintenanceController.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java

- 제목 : feat(116): 정비 등록
<br/>
- 정비 등록
<br/>
- 백엔드 crud 리엑트와 연결
<br/>
- [backend #116](이슈 주소)
<br/>

[2024-07-22] 정비 등록

---

src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java
src/main/java/com/finalproject/airport/facilities/controller/FacilitiesController.java
src/main/java/com/finalproject/airport/facilities/dto/FacilitiesDTO.java
src/main/java/com/finalproject/airport/facilities/entity/FacilitesType.java
src/main/java/com/finalproject/airport/facilities/entity/FacilitiesEntity.java
src/main/java/com/finalproject/airport/facilities/repository/FacilitiesRepository.java
src/main/java/com/finalproject/airport/facilities/service/FacilitiesService.java
src/main/resources/application.yml

- 제목 : #121 
<br/>
편의시설 등록 , 수정 , 삭제 추가 하였음 
<br/>
편의 시설 등록
편의 시설 수정 
편의 시설 삭제
<br/>
백엔드 crud 리엑트와 연결
<br/>
-편의시설 등록 , 수정 , 삭제 추가 [ #121 ]
<br/>

[2024-07-22] 편의시설 등록 , 수정 , 삭제 추가

---

src/main/java/com/finalproject/airport/auth/config/CorsMvcConfig.java
src/main/java/com/finalproject/airport/auth/config/SecurityConfig.java
src/main/java/com/finalproject/airport/auth/controller/AuthController.java
src/main/java/com/finalproject/airport/member/dto/JoinDTO.java
src/main/java/com/finalproject/airport/member/dto/UserDTO.java
src/main/java/com/finalproject/airport/member/entity/UserEntity.java
src/main/java/com/finalproject/airport/member/repository/UserRepository.java
src/main/java/com/finalproject/airport/member/service/CustomUserDetails.java
src/main/java/com/finalproject/airport/member/service/JoinService.java
src/main/java/com/finalproject/airport/store/controller/StoreController.java

- 제목 : 회원가입 인증코드 발급 api 구현
<br/>
- 랜덤코드로 나머지값 null 생성
- 회원가입시 인증코드 api 로 인증
- 인증시 회원가입 폼으로 이동
- 회원가입시 null 로 비어있던 컬럼값 수정
<br/>
<br/>
- 이메일, 휴대폰 인증 
<br/>

회원가입 인증코드 발급 api 구현

---

src/main/java/com/finalproject/airport/inspection/controller/InspectionController.java
src/main/java/com/finalproject/airport/inspection/dto/InspectionDTO.java
src/main/java/com/finalproject/airport/inspection/dto/InspectionRegistDTO.java
src/main/java/com/finalproject/airport/inspection/entity/InspectionEntity.java

- 제목 : feat(issue 번호):  inspection 엔티티수정
- [2024.07-23] inspection 엔티티수정
<br/>
<br/>
<br/>

[2024.07-23] inspection 엔티티수정

---

src/main/java/com/finalproject/airport/airplane/airplane/controller/AirplaneController.java
src/main/java/com/finalproject/airport/member/service/JoinService.java

- 제목 : feat(issue 번호): 패스워드 오류
<br/>
- 회원가입시 패스워드 안들어가지는 오류 고침
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-23] 패스워드 오류

---

build.gradle
src/main/java/com/finalproject/airport/auth/controller/AuthController.java
src/main/java/com/finalproject/airport/member/dto/MailDTO.java
src/main/java/com/finalproject/airport/member/service/MailService.java
src/main/java/com/finalproject/airport/store/dto/AuthMailDTO.java

- 제목 : feat(#129 ):  메일 전송 구현
<br/>
- 메일 보내기 기능 구현
- 보낼 때 3~4초 걸리므로 프론트 에서 loading 잘 걸어줘야됨.
<br/>
<br/>
- 프론트 연결
<br/>

[2024-07-23] 메일 전송 구현

---

src/main/java/com/finalproject/airport/inspection/dto/InspectionDTO.java
src/main/java/com/finalproject/airport/inspection/respository/InspectionRepository.java
src/main/java/com/finalproject/airport/inspection/service/InspectionService.java

- 제목 : feat(issue 번호): inspection 수정 삭제 최종
<br/>
- inspection 수정 삭제 최종
<br/>
<br/>
- inspection 수정 삭제 최최종
<br/>
<br/>

[2024.07-23] inspection 수정 삭제 최종

---

build.gradle
src/main/java/com/finalproject/airport/auth/controller/AuthController.java
src/main/java/com/finalproject/airport/auth/util/SMSUtil.java
src/main/java/com/finalproject/airport/member/service/MailService.java
src/main/java/com/finalproject/airport/store/dto/AuthMailPhoneDTO.java

- 제목 : feat(#135 ):  SMS 인증 추가
<br/>
- 메일만 보내거나, 휴대폰만 보내거나 둘다 동시에 보내는거 나눠놓음.
- 
<br/>
<br/>
- 아이디/ 비번 찾기
<br/>
<br/>

[2024-07-23] SMS 인증 추가

---

src/main/java/com/finalproject/airport/approval/controller/ApprovalController.java
src/main/java/com/finalproject/airport/approval/dto/ApprovalDTO.java
src/main/java/com/finalproject/airport/approval/entity/ApprovalEntity.java
src/main/java/com/finalproject/airport/approval/entity/ApprovalStatusEntity.java
src/main/java/com/finalproject/airport/approval/entity/ApprovalTypeEntity.java
src/main/java/com/finalproject/airport/approval/repository/ApprovalRepository.java
src/main/java/com/finalproject/airport/approval/service/ApprovalService.java
src/main/java/com/finalproject/airport/storage/entity/StorageType.java

- 제목 : feat(131): 승인 전체 조회
<br/>
- 전체 시설물(비행기(체크인 카운터, 수화물 수취대, 탑승구), 점포, 창고, 편의시설) 전체 조회
<br/>
<br/>
- 전체 조회 리엑트와 연결
- 승인 상세 조회 + 연결
- 승인
<br/>
- [backend #131 ](이슈 주소)
<br/>

[2024-07-23] 승인 시설물 전체 조회

---

src/main/java/com/finalproject/airport/auth/controller/AuthController.java
src/main/java/com/finalproject/airport/member/dto/ChangeAboutDTO.java
src/main/java/com/finalproject/airport/member/service/JoinService.java
src/main/java/com/finalproject/airport/store/controller/StoreController.java

[2024-07-23] 프로필 api 추가

---

src/main/java/com/finalproject/airport/airplane/baggageclaim/dto/BaggageClaimDTO.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaim.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaimIsUse.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaimLocation.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java
src/main/java/com/finalproject/airport/airplane/checkincounter/dto/CheckinCounterDTO.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounter.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounterIsUse.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounterLocation.java
src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java
src/main/java/com/finalproject/airport/airplane/gate/dto/GateDTO.java
src/main/java/com/finalproject/airport/airplane/gate/entity/Gate.java
src/main/java/com/finalproject/airport/airplane/gate/entity/GateIsUse.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java

- 제목 : feat(issue 번호): 비행기 컬럼 변경
<br/>
- location, isUse enum 설정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-23] 비행기 관련 컬럼 변경

---

build.gradle
src/main/java/com/finalproject/airport/auth/config/SecurityConfig.java
src/main/java/com/finalproject/airport/auth/controller/AuthController.java
src/main/java/com/finalproject/airport/config/WebSocketConfig.java
src/main/java/com/finalproject/airport/member/dto/JoinDTO.java
src/main/java/com/finalproject/airport/member/entity/UserEntity.java
src/main/java/com/finalproject/airport/member/service/JoinService.java
src/main/java/com/finalproject/airport/store/controller/StoreController.java
src/main/java/com/finalproject/airport/store/dto/AuthMailPhoneDTO.java
src/main/java/com/finalproject/airport/store/dto/StoreAPIDTO.java
src/main/java/com/finalproject/airport/store/dto/StoreDTO.java
src/main/java/com/finalproject/airport/store/dto/StoreRegistDTO.java
src/main/java/com/finalproject/airport/webSocket/dto/ChatMessageDTO.java
src/main/java/com/finalproject/airport/webSocket/handler/WebSocketHandler.java

- 제목 : feat(#140 ): AuthController, DTO, StoreController, DTO swagger 명세 추가
<br/>
- 컨트롤러 dto swagger 명세 추가함
<br/>
<br/>

[2024-07-24] AuthController, DTO, StoreController, DTO swagger 명세 추가

---

src/main/java/com/finalproject/airport/approval/controller/ApprovalController.java
src/main/java/com/finalproject/airport/approval/repository/ApprovalRepository.java
src/main/java/com/finalproject/airport/approval/service/ApprovalService.java
src/main/resources/application.yml

- 제목 : feat(132): 승인 상세 조회
<br/>
- 아직 미완임 
- 중대적인 변화가 일어나 앞으로의 과제에 적겠음
<br/>
<br/>
- 승인의 상세 조회를 할때 각 시설물들의 정보들을 끌고 와서 승인을 해야 하기 떄문에 각 시설물들에 대한 전반적인 코드 수정이 필요
- 그 DB 들을 승인한테 보내줘서 상태 변경을 해줘야 함
<br/>
- [ backend #132 ](이슈 주소)
<br/>

[2024-07-24] 승인 상세 조회

---

build.gradle
src/main/java/com/finalproject/airport/airplane/airplane/DTO/AirplaneDTO.java
src/main/java/com/finalproject/airport/airplane/airplane/DTO/ArrivalAirplaneDTO.java
src/main/java/com/finalproject/airport/airplane/airplane/DTO/DepartureAirplaneDTO.java
src/main/java/com/finalproject/airport/airplane/airplane/Entity/Airplane.java
src/main/java/com/finalproject/airport/airplane/airplane/controller/AirplaneController.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/controller/BaggageClaimController.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/dto/BaggageClaimDTO.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaim.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaimIsUse.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java
src/main/java/com/finalproject/airport/airplane/checkincounter/controller/CheckinCounterController.java
src/main/java/com/finalproject/airport/airplane/checkincounter/dto/CheckinCounterDTO.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounter.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounterIsUse.java
src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java
src/main/java/com/finalproject/airport/airplane/gate/controller/GateController.java
src/main/java/com/finalproject/airport/airplane/gate/dto/GateDTO.java
src/main/java/com/finalproject/airport/airplane/gate/entity/Gate.java
src/main/java/com/finalproject/airport/airplane/gate/entity/GateIsUse.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java

- 제목 : feat(143): 비행기 관련 Swagger 추가
<br/>
- 비행기  Swagger 추가
- 체크인 카운터 Swagger 추가
- 탑승구 Swagger 추가
- 수화물 수취대 Swagger 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #143]
<br/>

[2024-07-24] 비행기 관련 Swagger 추가

---

src/main/java/com/finalproject/airport/auth/config/SecurityConfig.java
src/main/java/com/finalproject/airport/auth/util/SMSUtil.java
src/main/java/com/finalproject/airport/member/controller/AuthController.java
src/main/java/com/finalproject/airport/member/dto/UserFindIdDTO.java
src/main/java/com/finalproject/airport/member/dto/UserFindPasswordDTO.java
src/main/java/com/finalproject/airport/member/service/JoinService.java
src/main/java/com/finalproject/airport/member/service/MailService.java

- 제목 : #153
<br/>
- 임시 비밀번호 이메일,전화번호 발급 추가
<br/>
<br/>
- 모바일 페이지
<br/>
<br/>

[2024-07-25] 임시 비밀번호 이메일,전화번호 발급 추가

---

src/main/java/com/finalproject/airport/storage/controller/StorageController.java
src/main/java/com/finalproject/airport/storage/entity/StorageType.java

- 제목 : feat(145): storage swagger
<br/>
- storage swagger 작성
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #145 호](이슈 주소)
<br/>

[2024.07.24] storage swagger 작성

---

src/main/java/com/finalproject/airport/airplane/gate/dto/GateDTO.java
src/main/java/com/finalproject/airport/airplane/gate/entity/Gate.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java
src/main/java/com/finalproject/airport/approval/controller/ApprovalController.java
src/main/java/com/finalproject/airport/approval/dto/ApprovalDTO.java
src/main/java/com/finalproject/airport/approval/dto/GatecodeDTO.java
src/main/java/com/finalproject/airport/approval/entity/ApprovalEntity.java
src/main/java/com/finalproject/airport/approval/entity/ApprovalStatusEntity.java
src/main/java/com/finalproject/airport/approval/repository/ApprovalRepository.java
src/main/java/com/finalproject/airport/approval/service/ApprovalService.java

- 제목 : feat(156): 시설물 등록 승인
<br/>
- Gate에 관련된 정보를 gateCode로 승인에 가지고 와서 승인 DB에 저장
- 승인을 할 경우 approvalStatus 의 상태가 N에서 Y로 변하게 되고
- 동시에 시설물 Gate 의 isActive 도 N에서 Y로 변하게 된다. 
- 그럼 승인 완료
<br/>
<br/>
- 나머지 시설물 등록 코드 바꿔주기
- 시설물 수정 승인도 만들기
<br/>
- [backend #156 ](이슈 주소)
<br/>

[2024-07-25] 시설물_Gate 등록 승인

---

src/main/java/com/finalproject/airport/airplane/airplane/DTO/ArrivalAirplaneDTO.java
src/main/java/com/finalproject/airport/airplane/airplane/DTO/DepartureAirplaneDTO.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/dto/BaggageClaimDTO.java
src/main/java/com/finalproject/airport/airplane/checkincounter/dto/CheckinCounterDTO.java
src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java
src/main/java/com/finalproject/airport/airplane/gate/dto/GateDTO.java
src/main/java/com/finalproject/airport/member/controller/AuthController.java

- 제목 : feat(): 체크인카운터 / 수화물수취대 수정
<br/>
-체크인카운터 dto 수정
-  수화물수취대 dto 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-26] 체크인카운터 / 수화물수취대 수정

---

src/main/java/com/finalproject/airport/storage/dto/StorageDTO.java
src/main/java/com/finalproject/airport/storage/dto/StorageRegistDTO.java
src/main/java/com/finalproject/airport/storage/entity/StorageEntity.java
src/main/resources/application.yml

- 제목 : feat(158): storage column 추가
<br/>
- storage column 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #158 ](이슈 주소)
<br/>

[2024.07.24] storage column 추가

---

.env
build.gradle
src/main/java/com/finalproject/airport/equipment/controller/EquipmentController.java
src/main/resources/application.yml

- 제목 : #164  [2024.07-26] equipment 상세조회
<br/>
-  equipment 상세조회
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024.07-26] equipment 상세조회

---

src/main/java/com/finalproject/airport/airplane/airplane/DTO/DepartureAirplaneDTO.java

- 제목 : feat(143):  DTO swagger 추가
<br/>
- DTO swagger 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #143](이슈 주소)
<br/>

[2024-07-26] DTO swagger 추가

---

build.gradle
src/main/java/com/finalproject/airport/inspection/entity/InspectionEntity.java
src/main/java/com/finalproject/airport/manager/dto/UserFindManagerDTO.java
src/main/java/com/finalproject/airport/manager/entity/ManagersEntity.java
src/main/java/com/finalproject/airport/manager/repository/ManagersRepository.java
src/main/java/com/finalproject/airport/manager/service/ManagersService.java
src/main/java/com/finalproject/airport/member/controller/AuthController.java
src/main/java/com/finalproject/airport/member/dto/UserContactDTO.java
src/main/java/com/finalproject/airport/member/dto/UserDTO.java
src/main/java/com/finalproject/airport/member/entity/UserEntity.java
src/main/java/com/finalproject/airport/member/service/CustomUserDetails.java
src/main/java/com/finalproject/airport/member/service/UserService.java

- 제목 :[2024-07-26] 편의시설 담당자 조회 api 추가
<br/>
- [2024-07-26] 편의시설 담당자 조회 api 추가
<br/>
- 추가 삭제 기능 추가
<br/>
<br/>

[2024-07-26] 편의시설 담당자 조회 api 추가

---

src/main/java/com/finalproject/airport/manager/repository/ManagersRepository.java
src/main/java/com/finalproject/airport/manager/service/ManagersService.java
src/main/java/com/finalproject/airport/storage/controller/StorageController.java
src/main/java/com/finalproject/airport/storage/entity/StorageEntity.java
src/main/java/com/finalproject/airport/storage/service/StorageService.java

- 제목 : 창고, 편의시설 담당자 추가
<br/>
- 창고, 편의시설 담당자 추가
<br/>
<br/>
- 비행기 담당자 추가
- 웹소켓 설정
<br/>

[2024-07-26] 창고, 편의시설 담당자 추가

---

src/main/java/com/finalproject/airport/airplane/airplane/controller/AirplaneController.java
src/main/java/com/finalproject/airport/airplane/airplane/repository/AirplaneRepository.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/dto/BaggageClaimDTO.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java
src/main/java/com/finalproject/airport/airplane/checkincounter/controller/CheckinCounterController.java
src/main/java/com/finalproject/airport/airplane/checkincounter/dto/CheckinCounterDTO.java
src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java

- 제목 : feat(170,171): 체크인 카운터 / 수화물 수취대 등록
<br/>
- 체크인 카운터 등록 backend와 연결
- 수화물 수취대 등록 backend와 연결
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #170 #171 ](이슈 주소)
<br/>

[2024-07-27] 체크인 카운터 / 수화물 수취대 등록

---

src/main/java/com/finalproject/airport/airplane/gate/controller/GateController.java
src/main/java/com/finalproject/airport/airplane/gate/dto/GateDTO.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java

- 제목 : feat(173): 탑승구 등록
<br/>
- 탑승구 등록 react 연결
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-28] 탑승구 등록

---

src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java
src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java
src/main/java/com/finalproject/airport/approval/dto/ApprovalDTO.java
src/main/java/com/finalproject/airport/approval/entity/ApprovalEntity.java
src/main/java/com/finalproject/airport/approval/service/ApprovalService.java

- 제목 : feat(175): 비행기 등록 승인
<br/>
- 체크인 카운터 등록시 승인 요청
- 탑승구 등록시 승인 요청
- 수화물 수취대 등록시 승인 요청
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #175](이슈 주소)
<br/>

[2024-07-28] 비행기 등록 승인

---

src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java
src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java
src/main/java/com/finalproject/airport/approval/controller/ApprovalController.java
src/main/java/com/finalproject/airport/approval/dto/ApprovalDTO.java
src/main/java/com/finalproject/airport/approval/entity/ApprovalEntity.java
src/main/java/com/finalproject/airport/approval/service/ApprovalService.java
src/main/java/com/finalproject/airport/facilities/controller/FacilitiesController.java
src/main/java/com/finalproject/airport/facilities/dto/FacilitiesDTO.java
src/main/java/com/finalproject/airport/facilities/entity/FacilitiesEntity.java
src/main/java/com/finalproject/airport/facilities/service/FacilitiesService.java
src/main/java/com/finalproject/airport/storage/service/StorageService.java

- 제목 : feat(180): 편의시설 승인 처리
<br/>
- 편의시설 등록할 때 정보가 승인 db 에 저장이 될 수 있도록 변경
- 승인 처
<br/>
<br/>
- 전체 조회와 상세 조회 리엑트 연결하기
<br/>
- [backend #180 ](이슈 주소)
<br/>

[2024-07-29] 편의시설 승인 처리

---

src/main/java/com/finalproject/airport/equipment/controller/EquipmentController.java
src/main/java/com/finalproject/airport/equipment/dto/EquipmentDTO.java
src/main/java/com/finalproject/airport/equipment/entity/EquipmentEntity.java
src/main/java/com/finalproject/airport/equipment/repository/EquipmentRepository.java
src/main/java/com/finalproject/airport/equipment/service/EquipmentService.java
src/main/java/com/finalproject/airport/inspection/controller/InspectionController.java
src/main/java/com/finalproject/airport/inspection/dto/InspectionDTO.java
src/main/java/com/finalproject/airport/inspection/dto/InspectionRegistDTO.java
src/main/java/com/finalproject/airport/inspection/respository/InspectionRepository.java
src/main/java/com/finalproject/airport/inspection/service/InspectionService.java

- 제목 : #182  [2024.07-29] inspection 등록, 장비재고 등록 빼고 기능 완성
<br/>
- inspection 등록, 장비재고 등록 빼고 기능 완성
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024.07-29] inspection 등록, 장비재고 등록 빼고 기능 완성

---

src/main/java/com/finalproject/airport/equipment/controller/EquipmentController.java
src/main/java/com/finalproject/airport/equipment/service/EquipmentService.java
src/main/java/com/finalproject/airport/inspection/dto/InspectionDTO.java

- 제목 #186  장비재고 등록 기능 완성
<br/>
-  장비재고 등록 기능 완성
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024.07.30] 장비재고 등록 기능 완성

---

src/main/java/com/finalproject/airport/airplane/checkincounter/controller/CheckinCounterController.java
src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java
src/main/java/com/finalproject/airport/airplane/gate/entity/Gate.java
src/main/java/com/finalproject/airport/airplane/gate/repository/GateRepository.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java
src/main/java/com/finalproject/airport/maintenance/controller/MaintenanceController.java
src/main/java/com/finalproject/airport/maintenance/dto/MaintenanceDTO.java
src/main/java/com/finalproject/airport/maintenance/entity/MaintenanceEntity.java
src/main/java/com/finalproject/airport/maintenance/entity/MaintenanceStatus.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java

- 제목 : feat(issue 번호): 안전점검 시설물 정보
<br/>
- 안전점검 시설물 위치 정보 가져오기
- 
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-30] 안전점검 시설물 정보

---

src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaim.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/repository/BaggageClaimRepository.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounter.java
src/main/java/com/finalproject/airport/airplane/checkincounter/repository/CheckinCounterRepository.java
src/main/java/com/finalproject/airport/airplane/gate/repository/GateRepository.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java
src/main/java/com/finalproject/airport/facilities/entity/FacilitiesEntity.java
src/main/java/com/finalproject/airport/facilities/repository/FacilitiesRepository.java
src/main/java/com/finalproject/airport/maintenance/controller/MaintenanceController.java
src/main/java/com/finalproject/airport/maintenance/dto/MaintenanceDTO.java
src/main/java/com/finalproject/airport/maintenance/entity/MaintenanceEntity.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java

- 제목 : feat(issue 번호):  안전점검 시설물 코드 추가
<br/>
-  안전점검 시설물 코드 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-07-31] 안전점검 시설물 코드 추가

---

src/main/java/com/finalproject/airport/approval/dto/ApprovalDTO.java
src/main/java/com/finalproject/airport/approval/service/ApprovalService.java
src/main/java/com/finalproject/airport/equipment/dto/EquipmentDTO.java
src/main/java/com/finalproject/airport/equipment/service/EquipmentService.java
src/main/java/com/finalproject/airport/facilities/dto/FacilitiesDTO.java
src/main/java/com/finalproject/airport/facilities/service/FacilitiesService.java
src/main/java/com/finalproject/airport/storage/dto/StorageDTO.java
src/main/java/com/finalproject/airport/storage/dto/StorageRegistDTO.java
src/main/java/com/finalproject/airport/storage/service/StorageService.java
src/main/java/com/finalproject/airport/store/dto/StoreDTO.java
src/main/java/com/finalproject/airport/store/dto/StoreRegistDTO.java
src/main/resources/application.yml

- 제목 : feat(issue 번호): DTO 네임 대 통합
<br/>
- DTO 네임 대 통합
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024.07.31] DTO 네임 대 통합

---

src/main/java/com/finalproject/airport/approval/entity/ApprovalEntity.java
src/main/java/com/finalproject/airport/equipment/entity/EquipmentEntity.java
src/main/java/com/finalproject/airport/facilities/entity/FacilitiesEntity.java
src/main/java/com/finalproject/airport/facilities/service/FacilitiesService.java
src/main/java/com/finalproject/airport/maintenance/entity/MaintenanceEntity.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java
src/main/java/com/finalproject/airport/storage/entity/StorageEntity.java
src/main/java/com/finalproject/airport/storage/service/StorageService.java
src/main/java/com/finalproject/airport/store/entity/StoreEntity.java

- 제목 : feat(issue 번호):엔티티 네임 대 통합
<br/>
- 엔티티 네임 대 통합
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024.07.31] 엔티티 네임 대 통합

---

src/main/java/com/finalproject/airport/facilities/controller/FacilitiesController.java
src/main/java/com/finalproject/airport/storage/repository/StorageRepository.java
src/main/java/com/finalproject/airport/storage/service/StorageService.java

(확인 후 지워주세요)
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024.07.31] 창고 전체조회 수정

---

src/main/java/com/finalproject/airport/airplane/baggageclaim/repository/BaggageClaimRepository.java
src/main/java/com/finalproject/airport/airplane/checkincounter/repository/CheckinCounterRepository.java
src/main/java/com/finalproject/airport/airplane/gate/repository/GateRepository.java
src/main/java/com/finalproject/airport/facilities/repository/FacilitiesRepository.java
src/main/java/com/finalproject/airport/maintenance/controller/MaintenanceController.java
src/main/java/com/finalproject/airport/maintenance/entity/MaintenanceEntity.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java
src/main/java/com/finalproject/airport/storage/entity/StorageEntity.java
src/main/java/com/finalproject/airport/storage/repository/StorageRepository.java
src/main/java/com/finalproject/airport/store/entity/StoreEntity.java
src/main/java/com/finalproject/airport/store/repository/StoreRepository.java

- 제목 : feat(197): 기능명
(확인 후 지워주세요)
<br/>
- 정비 등록시 시설물 정보 같이 등록
- 시설물 선택시 해당 시설물 위치 가져오기
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [vackend #197](이슈 주소)
<br/>

[2024-07-31]정비 등록 기능

---

src/main/java/com/finalproject/airport/webSocket/chat/dto/ChatMessageDTO.java
src/main/java/com/finalproject/airport/webSocket/handler/WebSocketHandler.java
src/main/resources/application.yml

- 제목 : 채팅 기능 완성
<br/>
- 온라인 상태 확인, 채팅 컴포넌트 이동 기능 추가
<br/>

[2024-07-31] 채팅 기능 완성

---

src/main/java/com/finalproject/airport/approval/controller/ApprovalController.java
src/main/java/com/finalproject/airport/approval/entity/ApprovalEntity.java
src/main/java/com/finalproject/airport/approval/service/ApprovalService.java
src/main/java/com/finalproject/airport/facilities/repository/FacilitiesRepository.java
src/main/java/com/finalproject/airport/storage/repository/StorageRepository.java

- 제목 : feat(188): 승인 시설물 전체 조회
<br/>
- 승인페이지에서 시설물들의 정보를 끌고 오기 가능
- 사용자 입장에서 매니저의 이름이 안보
<br/>
<br/>
<br/>
- [backend #188 ](이슈 주소)
<br/>

[2024-08-01] 승인 시설물 전체 조회

---

src/main/java/com/finalproject/airport/airplane/baggageclaim/repository/BaggageClaimRepository.java
src/main/java/com/finalproject/airport/airplane/checkincounter/repository/CheckinCounterRepository.java
src/main/java/com/finalproject/airport/airplane/gate/repository/GateRepository.java
src/main/java/com/finalproject/airport/facilities/repository/FacilitiesRepository.java
src/main/java/com/finalproject/airport/maintenance/controller/MaintenanceController.java
src/main/java/com/finalproject/airport/maintenance/dto/MaintenanceDTO.java
src/main/java/com/finalproject/airport/maintenance/entity/MaintenanceEntity.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java
src/main/java/com/finalproject/airport/storage/repository/StorageRepository.java
src/main/java/com/finalproject/airport/store/repository/StoreRepository.java

- 제목 : feat(197): 정비 시설물 조인
<br/>
- 정비 시설물 조인
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #197](이슈 주소)
<br/>

[2024-08-01]정비 시설물 조인

---

build.gradle
src/main/java/com/finalproject/airport/airplane/airplane/controller/AirplaneController.java
src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java
src/main/java/com/finalproject/airport/location/controller/LocationController.java
src/main/java/com/finalproject/airport/location/dto/LocationAPIDTO.java
src/main/java/com/finalproject/airport/location/dto/ZoneDTO.java
src/main/java/com/finalproject/airport/location/entity/LocationEntity.java
src/main/java/com/finalproject/airport/location/entity/ZoneEntity.java
src/main/java/com/finalproject/airport/location/repository/LocationRepository.java
src/main/java/com/finalproject/airport/location/repository/ZoneRepository.java
src/main/java/com/finalproject/airport/location/service/LocationService.java
src/main/java/com/finalproject/airport/store/dto/StoreDTO.java
src/main/java/com/finalproject/airport/store/entity/StoreEntity.java
src/main/java/com/finalproject/airport/store/service/StoreService.java

- 제목 : feat(#203 ): 위치 엔티티 추가 OPENAPI 점포 데이터 연결
<br/>
- DB 에서 위치 데이터 가져옴
- 데이터가 일정하지 않아서 오류가 있을 수 있음
<br/>
<br/>
- 각 시설물 당 연결
<br/>

[2024-08-01] 위치 엔티티 추가 OPENAPI 점포 데이터 연결

---

src/main/java/com/finalproject/airport/maintenance/dto/MaintenanceEquipmentDTO.java
src/main/java/com/finalproject/airport/maintenance/entity/MaintenanceEntity.java
src/main/java/com/finalproject/airport/maintenance/entity/MaintenanceEquipment.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java

(확인 후 지워주세요)
<br/>
- 정비 장비 엔티티 추가
- 정비 장비 DTO 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #206 ](이슈 주소)
<br/>

[2024-08-01] 정비 장비 엔티티 DTO 추가

---

src/main/java/com/finalproject/airport/location/controller/LocationController.java
src/main/java/com/finalproject/airport/location/repository/ZoneRepository.java
src/main/java/com/finalproject/airport/location/service/LocationService.java

- 제목 : feat(#205 ):[2024-08-01] 층수, 위치 엔티티 추가 OPENAPI 점포 데이터 연결
<br/>
- 층수, 위치 까지 가져옴
<br/>

[2024-08-01] 층수, 위치 엔티티 추가 OPENAPI 점포 데이터 연결

---

src/main/java/com/finalproject/airport/equipment/repository/EquipmentRepository.java
src/main/java/com/finalproject/airport/maintenance/controller/MaintenanceController.java
src/main/java/com/finalproject/airport/maintenance/dto/EquipmentQuantityDTO.java
src/main/java/com/finalproject/airport/maintenance/dto/MaintenanceEquipmentDTO.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java

- 제목 : feat(197): 정비 장비 등록
<br/>
- 정비에서 장비 등록 시 사용한 장비에 수량 차감
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #197 ](이슈 주소)
<br/>

[2024-08-02]정비 장비 등록

---

src/main/java/com/finalproject/airport/airplane/airplane/DTO/DepartureAirplaneDTO.java
src/main/java/com/finalproject/airport/facilities/controller/FacilitiesController.java
src/main/java/com/finalproject/airport/facilities/service/FacilitiesService.java
src/main/java/com/finalproject/airport/location/controller/LocationController.java
src/main/java/com/finalproject/airport/location/dto/FindZoneDTO.java
src/main/java/com/finalproject/airport/location/entity/LocationEntity.java
src/main/java/com/finalproject/airport/location/entity/ZoneEntity.java
src/main/java/com/finalproject/airport/location/repository/LocationRepository.java
src/main/java/com/finalproject/airport/location/repository/ZoneRepository.java
src/main/java/com/finalproject/airport/location/service/LocationService.java

[2024-08-02] 위치 조회, 저장 기능 중간

---

src/main/java/com/finalproject/airport/maintenance/controller/MaintenanceController.java
src/main/java/com/finalproject/airport/maintenance/dto/MaintenanceDTO.java
src/main/java/com/finalproject/airport/maintenance/entity/MaintenanceEntity.java
src/main/java/com/finalproject/airport/maintenance/entity/MaintenanceEquipment.java
src/main/java/com/finalproject/airport/maintenance/repository/MaintenanceEquipmentRepository.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java

- 제목 : feat(197): 정비 장비 재고 등록/가격 등록
<br/>
- 정비 장비 재고 등록
- 장비 가격따라 비용 등록
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #197](이슈 주소)
<br/>

[2024-08-02]정비 장비 재고 등록/가격 등록

---

build.gradle
src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java
src/main/java/com/finalproject/airport/equipment/controller/EquipmentController.java
src/main/java/com/finalproject/airport/equipment/dto/EquipmentDTO.java
src/main/java/com/finalproject/airport/equipment/entity/EquipmentEntity.java
src/main/java/com/finalproject/airport/equipment/service/EquipmentService.java
src/main/java/com/finalproject/airport/location/controller/LocationController.java
src/main/java/com/finalproject/airport/location/entity/LocationEntity.java
src/main/java/com/finalproject/airport/location/entity/ZoneEntity.java
src/main/java/com/finalproject/airport/location/repository/LocationRepository.java
src/main/java/com/finalproject/airport/location/service/LocationService.java
src/main/java/com/finalproject/airport/manager/entity/ManagersEntity.java
src/main/java/com/finalproject/airport/manager/repository/ManagersRepository.java
src/main/java/com/finalproject/airport/manager/service/ManagersService.java
src/main/resources/application.yml

- 제목 : feat(#204 ): 시설물 위치 저장, 수정 
<br/>
- 기능에서 어떤 부분이
<br/>
- 나머지 시설물 적용
<br/>

[2024-08-03] 시설물 위치 저장, 수정 

---

src/main/java/com/finalproject/airport/location/repository/LocationRepository.java
src/main/java/com/finalproject/airport/location/service/LocationService.java
src/main/java/com/finalproject/airport/manager/repository/ManagersRepository.java
src/main/java/com/finalproject/airport/manager/service/ManagersService.java

- 제목 : 위치/담당자 조회 Nullpointer 예외처리
<br/>
- 위치/담당자 조회 Nullpointer 예외처리

[2024-08-03] 위치/담당자 조회 Nullpointer 예외처리

---

src/main/java/com/finalproject/airport/airplane/airplane/DTO/AirplaneDTO.java
src/main/java/com/finalproject/airport/airplane/airplane/controller/AirplaneController.java
src/main/java/com/finalproject/airport/airplane/airplane/repository/AirplaneRepository.java
src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java
src/main/java/com/finalproject/airport/airplane/gate/controller/GateController.java
src/main/java/com/finalproject/airport/airplane/gate/dto/GateDTO.java
src/main/java/com/finalproject/airport/airplane/gate/entity/Gate.java
src/main/java/com/finalproject/airport/airplane/gate/repository/GateRepository.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java
src/main/java/com/finalproject/airport/config/BeanConfiguration.java
src/main/java/com/finalproject/airport/config/WebClientConfig.java

- 제목 : feat(issue 번호): #216 
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
#216 
<br/>

[2024-08-04] 탑승구 api 불러오기

---

.gitignore
src/main/java/com/finalproject/airport/AirportApplication.java
src/main/java/com/finalproject/airport/QRCode/controller/QRController.java
src/main/java/com/finalproject/airport/QRCode/dto/BaggageClaimQRDTO.java
src/main/java/com/finalproject/airport/QRCode/dto/CheckInCounterQRDTO.java
src/main/java/com/finalproject/airport/QRCode/dto/FacilityQRDTO.java
src/main/java/com/finalproject/airport/QRCode/dto/GateQRDTO.java
src/main/java/com/finalproject/airport/QRCode/dto/QRAllDTO.java
src/main/java/com/finalproject/airport/QRCode/dto/StorageQRDTO.java
src/main/java/com/finalproject/airport/QRCode/dto/StoreQRDTO.java
src/main/java/com/finalproject/airport/QRCode/service/QRService.java
src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/dto/BaggageClaimDTO.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaim.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounter.java

- 제목 : feat(#220 ): 시설물 QR 코드 발급 로직 추가
<br/>
- 시설물별 switch 로 나누기
- 
<br/>

[2024-08-05] 시설물 QR 코드 발급 로직 추가

---

src/main/java/com/finalproject/airport/equipment/controller/EquipmentController.java
src/main/java/com/finalproject/airport/equipment/dto/EquipmentDTO.java
src/main/java/com/finalproject/airport/equipment/entity/EquipmentCategory.java
src/main/java/com/finalproject/airport/equipment/entity/EquipmentEntity.java
src/main/java/com/finalproject/airport/equipment/service/EquipmentService.java

(확인 후 지워주세요)
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-05]장비 컬럼 수정

---

src/main/java/com/finalproject/airport/equipment/entity/EquipmentEntity.java

- 제목 : feat(226): 장비 기본이미지 등록
<br/>
- 장비 기본이미지 등록
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #226 ](이슈 주소)
<br/>

[2024-08-06]장비 기본이미지 등록

---

src/main/java/com/finalproject/airport/QRCode/controller/QRController.java
src/main/java/com/finalproject/airport/QRCode/dto/FacilityDetailDTO.java
src/main/java/com/finalproject/airport/QRCode/dto/JoinQRDTO.java
src/main/java/com/finalproject/airport/QRCode/service/QRService.java
src/main/java/com/finalproject/airport/inspection/entity/InspectionEntity.java

- 제목 : feat(issue 번호):  시설물 QR api 추가
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-06] 시설물 QR api 추가

---

src/main/java/com/finalproject/airport/airplane/baggageclaim/repository/BaggageClaimRepository.java
src/main/java/com/finalproject/airport/airplane/checkincounter/repository/CheckinCounterRepository.java
src/main/java/com/finalproject/airport/airplane/gate/repository/GateRepository.java
src/main/java/com/finalproject/airport/facilities/repository/FacilitiesRepository.java
src/main/java/com/finalproject/airport/inspection/controller/InspectionController.java
src/main/java/com/finalproject/airport/inspection/service/InspectionService.java
src/main/java/com/finalproject/airport/storage/repository/StorageRepository.java
src/main/java/com/finalproject/airport/store/repository/StoreRepository.java

- 제목 #231 : 안전점검 대쉬보드
<br/>
- 안전점검 대쉬보드
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-05] 안전 점검 데이터 차트

---

src/main/java/com/finalproject/airport/approval/controller/ApprovalController.java
src/main/java/com/finalproject/airport/approval/dto/ApprovalDTO.java
src/main/java/com/finalproject/airport/approval/entity/ApprovalEntity.java
src/main/java/com/finalproject/airport/approval/service/ApprovalService.java
src/main/java/com/finalproject/airport/maintenance/controller/MaintenanceController.java

- 제목 : feat(236): 승인 알림 기능
<br/>
- 승인 알림 체크 컬럼 추가
- 승인 등록/수정 시간 dto 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [backend #236](이슈 주소)
<br/>

[2024-08-08]승인 알림 기능

---

src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/controller/BaggageClaimController.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaim.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java
src/main/java/com/finalproject/airport/approval/controller/ApprovalController.java
src/main/java/com/finalproject/airport/approval/dto/ApprovalDTO.java
src/main/java/com/finalproject/airport/approval/entity/ApprovalEntity.java
src/main/java/com/finalproject/airport/approval/service/ApprovalService.java

- 제목 : feat(issue 238): 수하물 수취대 승인 수정
<br/>
- 수하물 수취대 내용 수정 시, 
- 관리자 승인 후, 수정 완료
<br/>
<br/>
- 나머지 시설물 승인 수정하기
<br/>
- [backend #238 ](이슈 주소)
<br/>

[2024-08-08] 수하물 수취대 승인 수정

---

src/main/java/com/finalproject/airport/QRCode/dto/QRAllDTO.java
src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java
src/main/java/com/finalproject/airport/auth/config/CorsMvcConfig.java
src/main/java/com/finalproject/airport/auth/config/SecurityConfig.java
src/main/java/com/finalproject/airport/manager/service/ManagersService.java
src/main/java/com/finalproject/airport/member/controller/AuthController.java
src/main/java/com/finalproject/airport/member/controller/UserController.java
src/main/java/com/finalproject/airport/member/dto/NewUserDTO.java
src/main/java/com/finalproject/airport/member/dto/NewUserDetailDTO.java
src/main/java/com/finalproject/airport/member/dto/SetRoleAndDepartmentDTO.java
src/main/java/com/finalproject/airport/member/entity/UserEntity.java
src/main/java/com/finalproject/airport/member/repository/UserRepository.java
src/main/java/com/finalproject/airport/member/service/JoinService.java

- 제목 : 시큐리티 추가/ 권한 관리 기능 추가(관)  ex) feat(17): pull request template 작성
<br/>
- 시큐리티 추가
- 권한 부여 기능 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-08] 시큐리티 추가/ 권한 관리 기능 추가(관)

---

src/main/java/com/finalproject/airport/airplane/airplane/controller/AirplaneController.java
src/main/java/com/finalproject/airport/airplane/gate/controller/GateController.java
src/main/java/com/finalproject/airport/airplane/gate/entity/Gate.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java

- 제목 : #248 
<br/>
- 탑승구 4구역 분할 조회 
<br/>
<br/>
- 수화물 수취대 연결
<br/>
#248 
<br/>

[2024-08-08] 탑승구 4구역 분할 조회 

---

src/main/java/com/finalproject/airport/approval/controller/ApprovalController.java
src/main/java/com/finalproject/airport/approval/service/ApprovalService.java
src/main/java/com/finalproject/airport/storage/controller/StorageController.java
src/main/java/com/finalproject/airport/storage/service/StorageService.java
src/main/java/com/finalproject/airport/store/controller/StoreController.java
src/main/java/com/finalproject/airport/store/repository/StoreRepository.java
src/main/java/com/finalproject/airport/store/service/StoreService.java

- 제목 : feat(issue 241,242): 점포, 창고 수정 승인
<br/>
- 점포, 창고 수정할 때 승인 받아야 하는 부분 처리 완
<br/>
<br/>
- 한번 다시 다 점검하고 프론트 정리하기
<br/>
- [backend #241 #242 ](이슈 주소)
<br/>

[2024-08-09] 점포, 창고 수정 승인

---

src/main/java/com/finalproject/airport/approval/controller/ApprovalController.java
src/main/java/com/finalproject/airport/facilities/entity/FacilitiesEntity.java
src/main/java/com/finalproject/airport/facilities/service/FacilitiesService.java

- 제목 : feat(issue 243): 편의시설 승인 수정을 수정
<br/>
- 편의시설 승인 수정을 수정
<br/>
- 프론트 정리
<br/>
- [backend #243 ](이슈 주소)
<br/>

[2024-08-09] 편의시설 승인 수정을 수정

---

src/main/java/com/finalproject/airport/airplane/airplane/Entity/ArrivalAirplane.java
src/main/java/com/finalproject/airport/airplane/airplane/repository/ArrivalAirplaneRepository.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/controller/BaggageClaimController.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/dto/BaggageClaimDTO.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaim.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/repository/BaggageClaimRepository.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java
src/main/java/com/finalproject/airport/airplane/gate/controller/GateController.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java

[2024-08-09] 수화물 수취대 DTO,엔티티 수정

---

src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java
src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java
src/main/java/com/finalproject/airport/approval/entity/ApprovalEntity.java
src/main/java/com/finalproject/airport/approval/service/ApprovalService.java

- 제목 : feat(issue 238,239,240): 비행기 관련 승인 수정을 수정
<br/>
- 비행기 관련 승인 수정을 수정
<br/>
- [backend #239 #238 #240 ](이슈 주소)
<br/>

[2024-08-09] 비행기 관련 승인 수정을 수정

---

src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java
src/main/java/com/finalproject/airport/manager/repository/ManagersRepository.java
src/main/java/com/finalproject/airport/manager/service/ManagersService.java
src/main/java/com/finalproject/airport/member/service/JoinService.java

- 제목 : 탑승구 담당자 연결
<br/>
- 탑승구 담당자 연결
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-09] 탑승구 담당자 연결

---

src/main/java/com/finalproject/airport/QRCode/dto/BaggageClaimQRDTO.java
src/main/java/com/finalproject/airport/QRCode/dto/GateQRDTO.java
src/main/java/com/finalproject/airport/QRCode/service/QRService.java
src/main/java/com/finalproject/airport/airplane/airplane/controller/AirplaneController.java
src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java

- 제목 : 안전점검 api 수정
<br/>
- 안전점검 api 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-09] 안전점검 api 수정

---

src/main/java/com/finalproject/airport/QRCode/service/QRService.java
src/main/java/com/finalproject/airport/config/RestTemplateConfig.java
src/main/java/com/finalproject/airport/gptapi/controller/GPTController.java
src/main/java/com/finalproject/airport/gptapi/dto/request/GPTRequestDTO.java
src/main/java/com/finalproject/airport/gptapi/dto/response/GPTResponseDTO.java
src/main/java/com/finalproject/airport/gptapi/service/GPTService.java
src/main/java/com/finalproject/airport/inspection/entity/InspectionEntity.java

- 제목 :[2024-08-10] gpt api 연동
<br/>
-  gpt api 연동 보고서 자동 생성
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-10] gpt api 연동

---

src/main/java/com/finalproject/airport/config/SwaggerConfig.java
src/main/java/com/finalproject/airport/webSocket/handler/WebSocketHandler.java

- 제목 : 긴급 상황 발생 시 경고 시스템
<br/>
- 긴급 상황 발생 시 경고 시스템
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-10] 긴급 상황 발생 시 경고 시스템

---

src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java
src/main/java/com/finalproject/airport/member/controller/UserController.java
src/main/java/com/finalproject/airport/member/dto/ImgAndNameDTO.java
src/main/java/com/finalproject/airport/member/service/UserService.java

- 제목 : 웹소켓 이미지/이름 Api 추가
<br/>
- 웹소켓 이미지/이름 Api 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-10] 웹소켓 이미지/이름 Api 추가

---

.env
build.gradle
src/main/java/com/finalproject/airport/airplane/airplane/repository/DepartureAirplaneRepository.java
src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/controller/BaggageClaimController.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaim.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java
src/main/java/com/finalproject/airport/airplane/checkincounter/controller/CheckinCounterController.java
src/main/java/com/finalproject/airport/airplane/checkincounter/dto/CheckinCounterDTO.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounter.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounterLocation.java
src/main/java/com/finalproject/airport/airplane/checkincounter/repository/CheckinCounterRepository.java
src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java

- 제목 : #256 
<br/>
- 수화물 수취대 값 DB에 넣기
<br/>
<br/>
- 디테일잡기
#256 
<br/>

[2024-08-10]수화물 수취대 값 DB에 넣기

---

src/main/java/com/finalproject/airport/QRCode/service/QRService.java
src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/controller/BaggageClaimController.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java
src/main/java/com/finalproject/airport/airplane/checkincounter/controller/CheckinCounterController.java
src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java
src/main/java/com/finalproject/airport/airplane/gate/controller/GateController.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java
src/main/java/com/finalproject/airport/approval/controller/ApprovalController.java
src/main/java/com/finalproject/airport/approval/service/ApprovalService.java
src/main/java/com/finalproject/airport/equipment/service/EquipmentService.java
src/main/java/com/finalproject/airport/facilities/service/FacilitiesService.java
src/main/java/com/finalproject/airport/inspection/service/InspectionService.java
src/main/java/com/finalproject/airport/location/service/LocationService.java
src/main/java/com/finalproject/airport/maintenance/controller/MaintenanceController.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java
src/main/java/com/finalproject/airport/manager/service/ManagersService.java
src/main/java/com/finalproject/airport/member/service/JoinService.java
src/main/java/com/finalproject/airport/member/service/MailService.java
src/main/java/com/finalproject/airport/member/service/UserService.java
src/main/java/com/finalproject/airport/storage/service/StorageService.java
src/main/java/com/finalproject/airport/store/repository/StoreRepository.java
src/main/java/com/finalproject/airport/store/service/StoreService.java
src/main/java/com/finalproject/airport/webSocket/handler/WebSocketHandler.java

- 제목 : 로깅 처리 초안
<br/>
- 로깅 처리 초안
- 각자 정리하기
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-11] 로깅 처리 초안

---

src/main/java/com/finalproject/airport/gptapi/controller/GPTController.java
src/main/java/com/finalproject/airport/gptapi/dto/request/GPTRequestDTO.java
src/main/java/com/finalproject/airport/gptapi/dto/response/AIInfoResponseDTO.java
src/main/java/com/finalproject/airport/gptapi/service/GPTService.java

- 제목 :ai 질문하기 기능 추가
<br/>
- ai 질문하기 기능 추가
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-11] ai 질문하기 기능 추가

---

src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java
src/main/java/com/finalproject/airport/auth/util/SMSUtil.java
src/main/java/com/finalproject/airport/member/service/MailService.java

- 제목 :  문자인증 skycare 변경
<br/>
-  문자인증 skycare 변경
- 
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-11] 문자인증 skycare 변경

---

src/main/java/com/finalproject/airport/airplane/airplane/service/AirPlaneService.java
src/main/java/com/finalproject/airport/equipment/controller/EquipmentController.java
src/main/java/com/finalproject/airport/equipment/dto/EquipmentStorageDTO.java
src/main/java/com/finalproject/airport/equipment/service/EquipmentService.java
src/main/java/com/finalproject/airport/webSocket/handler/WebSocketHandler.java

- 제목 :위치 수정
<br/>
- 위치 컬럼 수정
- 위치 인풋 태그 수정
- 장비 위치 창고로만 있게 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-12] 위치 수정

---

src/main/java/com/finalproject/airport/airplane/airplane/controller/AirplaneController.java
src/main/java/com/finalproject/airport/airplane/gate/dto/GateDTO.java
src/main/java/com/finalproject/airport/airplane/gate/entity/Gate.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java
src/main/java/com/finalproject/airport/storage/controller/StorageController.java
src/main/java/com/finalproject/airport/storage/service/StorageService.java

- 제목 : #273 
<br/>
- 게이트 앤티티 DTO 추가
<br/>
<br/>
- 발표준비
<br/>
#273 
<br/>

[2024-08-12] 게이트 앤티티 DTO 추가

---

src/main/java/com/finalproject/airport/storage/controller/StorageController.java
src/main/java/com/finalproject/airport/storage/dto/StorageDTO.java
src/main/java/com/finalproject/airport/storage/entity/StorageEntity.java
src/main/java/com/finalproject/airport/storage/service/StorageService.java

- 제목 : #275 
<br/>
- 창고 엔티티 DTO 수정
<br/>
<br/>
- 발표준비
<br/>
#275 
<br/>

[2024-08-12] 창고 엔티티 DTO 수정

---

src/main/java/com/finalproject/airport/airplane/checkincounter/dto/CheckinCounterDTO.java
src/main/java/com/finalproject/airport/airplane/checkincounter/entity/CheckinCounter.java
src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java

- 제목 : #278 
<br/>
- 체크인카운터 디테일 DB 값전달
<br/>
<br/>
- 발표준비
<br/>
#278 
<br/>

[2024-08-12] 체크인카운터 디테일 DB 값전달

---

src/main/java/com/finalproject/airport/airplane/baggageclaim/dto/BaggageClaimDTO.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/entity/BaggageClaim.java
src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java

- 제목 : #280 
<br/>
- 수화물 수취대 디테일 DB값 수정2
<br/>
<br/>
- 발표준비
<br/>
#280 
<br/>

[2024-08-12] 수화물 수취대 디테일 DB값 수정2

---

src/main/java/com/finalproject/airport/approval/service/ApprovalService.java
src/main/java/com/finalproject/airport/facilities/controller/FacilitiesController.java
src/main/java/com/finalproject/airport/facilities/service/FacilitiesService.java

- 제목 : feat(issue 번호): 편의시설 승인 오류 수정
<br/>
- 편의시설 승인 오류 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-12]편의시설 승인 오류 수정

---

src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java

- 제목 : #283 
<br/>
- 체크인 카운터 오류수정
<br/>
<br/>
- 발표 준비
<br/>
#283 
<br/>

[2024-08-13] 체크인 카운터 오류수정

---

src/main/java/com/finalproject/airport/facilities/service/FacilitiesService.java

- 제목 : feat(issue 번호): 편의시설 승인 오류 수정
<br/>
- 편의시설 승인 오류 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13]편의시설 승인 오류 수정

---

src/main/java/com/finalproject/airport/storage/service/StorageService.java

- 제목 : feat(issue 번호): 승인 오류
<br/>
- 승인 오류
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13]승인 오류 수정

---

src/main/java/com/finalproject/airport/storage/service/StorageService.java

- 제목 : feat(issue 번호): 창고 수정 승인
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13]창고 수정 승인

---

src/main/java/com/finalproject/airport/approval/service/ApprovalService.java

- 제목 : [2024-08-13] 담당자 승인 수정
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] 담당자 승인 수정

---

src/main/java/com/finalproject/airport/airplane/gate/repository/GateRepository.java
src/main/java/com/finalproject/airport/maintenance/service/MaintenanceService.java
src/main/java/com/finalproject/airport/storage/repository/StorageRepository.java
src/main/java/com/finalproject/airport/store/repository/StoreRepository.java

- 제목 : feat(issue 번호): 정비 오류 수정
<br/>
- 정비 오류 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13]정비 오류 수정

---

src/main/java/com/finalproject/airport/manager/entity/ManagersEntity.java
src/main/java/com/finalproject/airport/manager/repository/ManagersRepository.java
src/main/java/com/finalproject/airport/manager/service/ManagersService.java

- 제목 : 담당자 추가
<br/>
- 기능에서 어떤 부분이
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] 담당자 추가

---

src/main/java/com/finalproject/airport/approval/controller/ApprovalController.java
src/main/java/com/finalproject/airport/approval/dto/ApprovalDTO.java
src/main/java/com/finalproject/airport/approval/entity/ApprovalEntity.java
src/main/java/com/finalproject/airport/approval/service/ApprovalService.java

- 제목 : feat(issue 번호): ]알림 기능
<br/>
- ]알림 기능
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13]알림 기능

---

src/main/java/com/finalproject/airport/auth/util/SMSUtil.java
src/main/java/com/finalproject/airport/member/service/MailService.java
src/main/java/com/finalproject/airport/webSocket/chat/service/ChatService.java
src/main/java/com/finalproject/airport/webSocket/handler/WebSocketHandler.java

- 제목 : [2024-08-13] url 업데이트
<br/>
- [2024-08-13] url 업데이트
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13] url 업데이트

---

src/main/java/com/finalproject/airport/airplane/baggageclaim/service/BaggageClaimService.java
src/main/java/com/finalproject/airport/airplane/checkincounter/service/CheckinCounterService.java
src/main/java/com/finalproject/airport/airplane/gate/service/GateService.java
src/main/java/com/finalproject/airport/approval/entity/ApprovalEntity.java
src/main/java/com/finalproject/airport/facilities/service/FacilitiesService.java
src/main/java/com/finalproject/airport/storage/service/StorageService.java
src/main/java/com/finalproject/airport/store/service/StoreService.java

- 제목 : feat(issue 번호): 오류 수정
<br/>
- 오류 수정
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
<br/>

[2024-08-13]오류 수정
